language: node_js

install:
  - npm install

script:
  - npm run build
  - npm run test

after_success:
  - npm install -g codecov
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && codecov

node_js:
  - 'stable'
